use_frameworks!

platform :ios, '10.0'

target 'YSCurrencyAnimLabel_Example' do
  pod 'YSCurrencyAnimLabel', :path => '../'

  target 'YSCurrencyAnimLabel_Tests' do
    inherit! :search_paths

    
  end
end
